### PR TITLE
Fix issue14 update ref

### PR DESCRIPTION
**Pull request by fpfeng**
### Deps setup
```
    driver1.0.12: xoa-driver==1.0.12
    core1.0.7: xoa-core==1.0.7
    coregitmain: git+https://github.com/xenanetworks/open-automation-core.git@main
    convertergitfix: git+https://github.com/xenanetworks/open-automation-config-converter.git@fix-issue14-update-ref
```

### Test was passed on following deps combination
```
  driver1.0.12-core1.0.7-convertergitfix: OK (86.58=setup[21.88]+cmd[64.70] seconds)
  driver1.0.12-coregitmain-convertergitfix: OK (92.41=setup[27.70]+cmd[64.70] seconds)
  congratulations :) (179.02 seconds)
`````

### Test content
```
suite_for_testing = [
    TestSuiteInfo(suite_type=TestSuiteType.RFC2544, valkyrie_config_path=VALKYRIE_CONFIG_FILE_2544),
    TestSuiteInfo(suite_type=TestSuiteType.RFC2889, valkyrie_config_path=VALKYRIE_CONFIG_FILE_2889),
]


@pytest.mark.asyncio
async def test_plugins(tester_197):
    xoa_controller = await controller.MainController()
    xoa_controller.register_lib( str(PATH_PLUGINS) )
    await xoa_controller.add_tester(tester_197)

    for test_suite in suite_for_testing:
        info = xoa_controller.get_test_suite_info(test_suite.suite_type.value)
        assert info
        with open(test_suite.valkyrie_config_path, "r") as f:
            new_data = converter(test_suite.suite_type, f.read(), info["schema"])
            new_config = json.loads(new_data)
            execution_id = xoa_controller.start_test_suite(test_suite.suite_type.value, new_config)
            async for msg in xoa_controller.listen_changes(execution_id, _filter={types.EMsgType.STATISTICS}):
                assert msg
```

### CODE REVIEW

**Comment by fpfeng** [comment]
https://github.com/xenanetworks/open-automation-test-suites/pull/15 
merge at the same time please.

**Review by ArtemConstantinov — APPROVED** [review]
The code looks fine to me.

**Comment by fpfeng** [comment]
@leonardhyu we have question about enum so hold off merge please.

**Comment by leonardhyu** [comment]
Sure

Best regards,
Leo

Leonard Yu
Senior Product Manager
Xena Networks
***@***.***
________________________________

**Pull request merged**
